spring:
  flyway:
    locations: classpath:migrations
    url: jdbc:postgresql://192.168.6.13:5432/yuliadb
    user: yulia
    password: yulia

  datasource:
    url: jdbc:postgresql://192.168.6.13:5432/yuliadb
    username: yulia
    password: yulia
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # create-drop


server:
  port: 8192

csvPath: "/tasks.csv"

